Results of team report / report text
medizininformatik-initiative/kerndatensatz-bildgebung pull request #13
Opened 2024-01-30 14:23 UTC by johannes-kast-mint

2024-02-06 10:29 UTC, lucscherer requested changes
Wir sollten noch über die finalen Naming-Conventions schauen, aber allgemein sind die Unterschiede ja marginal

2024-03-26 13:42 UTC, noemide commented on input/fsh/profiles/Profile-DiagnosticReport.fsh
> +* category.coding[diagnostic-service-sections] = $DSS#RAD "Radiology"
Ist das ein Radlex Code?

2024-03-26 13:42 UTC, noemide commented on input/fsh/profiles/Profile-DiagnosticReport.fsh
> -* basedOn 1..* MS
Drinlassen da ServiceRequest genutzt wird

2024-03-26 13:43 UTC, noemide commented on input/fsh/profiles/Profile-DiagnosticReport.fsh
> +* extension contains Supporting_Info named supportingInfo 0..* MS
Backport Extension, wie einbinden?

2024-03-26 13:49 UTC, noemide commented on input/fsh/profiles/Profile-DiagnosticReport.fsh
> +* specimen 0..0
Specimen erlauben

2024-03-26 14:00 UTC, noemide commented on input/fsh/profiles/Profile-DiagnosticReport.fsh
> -* conclusion MS
Conclusion drinlassen

2024-03-27 12:11 UTC, lucscherer commented on input/fsh/profiles/Profile-DiagnosticReport.fsh
> +* category.coding[diagnostic-service-sections] = $DSS#RAD "Radiology"
Ist ein HL7 ValueSet kann drin bleiben

2024-03-27 13:18 UTC, lucscherer approved these changes

2024-03-27 13:19 UTC, merged